image: $SKA_K8S_TOOLS_DOCKER_BUILDER_IMAGE
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CI_POETRY_VERSION: 1.8.2
cache:
  paths:
    - build
stages:
  - build
  - test
  - lint
  - publish
  - pages
  - scan
include:
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/python.gitlab-ci.yml'
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs.gitlab-ci.yml'
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/release.gitlab-ci.yml'
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'

shell-test:
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y shunit2 zsh
  script:
    - make shell-test

changed-files-pre-commit:
  extends: python-lint
  stage: lint
  script:
    - poetry run pip install pre-commit
    - 'echo "Fetching target branch: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME"'
    - git fetch origin "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    - |
      CHANGED_FILES=$(git diff --name-only origin/"$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"...HEAD || true)
      echo "CHANGED_FILES=${CHANGED_FILES[@]}"
      echo "$CHANGED_FILES" | xargs pre-commit run --files
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

all-files-pre-commit:
  extends: python-lint
  stage: lint
  script:
    - poetry run pip install pre-commit
    - pre-commit run --all-files
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  allow_failure: true
