repos:
- repo: https://gitlab.com/calgray/ska-pre-commit-hooks
  rev: 13a5b7b0daf2916cb006870315b3d58019e5ec4a
  hooks:
  - id: isort
  - id: black
  - id: flake8
  - id: pylint
  - id: branch ticket id
  - id: commit msg ticket id
