repos:
- repo: https://gitlab.com/ska-telescope/templates/ska-pre-commit-hooks
  rev: 8ddc99f3f54da9cc474f1e9af4c8e9f19e2c37b1
  hooks:
  # python lint
  - id: isort
    args: [--check-only]
  - id: black
    args: [--check]
  - id: flake8
  - id: pylint
  # jira ticket
  - id: branch ticket id
  - id: commit msg ticket id
default_install_hook_types:
- pre-commit
- commit-msg
